import type { Metadata } from 'next';
import { nunito } from '@/components/fonts';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
